### ISSUE TITLE
Not sure how this works

### ISSUE THREAD

**Issue by aalvarado028** [andykais/ifunny-scraper#1]
Hello, I am very new to javascript and I cannot get this scraper to execute. i downloaded node.js and was able to install using the 'npm install -g ifunny-scraper' input into windows command line but now I have no idea how to employ the usage line. are the '<>' necessary? Can you please post an example format using an actual username and save file location? 

I also have no idea where I should be executing the usage commands and in which folder. Sorry for the dumb questions, but I am very new to this!

Thank you!!!!

**Comment by andykais** [comment]
Hi there, thanks for posting an issue! I just ran the scraper and discovered that the scraper was outputting a `404` and it turns out ifunny's routes have changed slightly.
```
ifunny-get oddlysatisyfying
Saving files to ~/ifunny_accounts
visiting memer profile...
Error: status code: 404 at https://ifunny.co/oddlysatisyfying
    at Request.request [as _callback] (/home/andrew/.npm-packages/lib/node_modules/scrape-ifunny/src/requester.js:23:16)
    at Request.self.callback (/home/andrew/.npm-packages/lib/node_modules/scrape-ifunny/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/andrew/.npm-packages/lib/node_modules/scrape-ifunny/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/andrew/.npm-packages/lib/node_modules/scrape-ifunny/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
the user's home page has changed from `https://ifunny.co/oddlysatisyfying` to `https://ifunny.co/user/oddlysatisyfying`. That is fixed now and published in a new package version `scrape-ifunny@1.0.2`. Just run this
```bash
npm uninstall -g scrape-ifunny
npm install -g scrape-ifunny
ifunny-get oddlysatisfying
```
(replace the user "oddlysatisfying" with whatever account you are trying to scrape). 

Also, just a tip for the future, if you try a command like this and it fails to run, it helps to include the output that the command did give to you so the project's developer can help diagnose the problem.

**Comment by aalvarado028** [comment]
Hello!

I was able to perform the uninstall and install, but the 'ifunny-get oddlysatisfying' command gives me a 'The system cannot find the path specified' error. See below for attached image.
![scraper output](https://user-images.githubusercontent.com/46057150/51409734-41e9e480-1b28-11e9-9526-c2efd35270f3.JPG)

Please help!

**Comment by andykais** [comment]
hey sorry for the late reply here, the notification for this library got buried (arg!). I dont have a windows pc on hand, so I cant be certain I fixed your issue, but it may have been a problem with windows paths vs linux paths, or with nested directory creation. I made both of those more consistent, and pushed the change in `scrape-ifunny@1.0.3`. If it still doesn't work, then let me know, I can do my best to get a windows pc to try and find the problem.
